import { test, expect } from "@playwright/test";
import path from "node:path";
test("desktop catalogue, filtering, verified checkout and editing", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.setViewportSize({ width: 1440, height: 1100 });
  await page.goto("/");
  await expect(page.getByRole("heading", { name: "This cycle’s good things." })).toBeVisible();
  await expect(page.locator(".product-card")).toHaveCount(6);
  for (const img of await page.locator(".product-photo img").all()) await expect.poll(() => img.evaluate((image) => (image as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);
  await page.screenshot({ path: "docs/screenshots/catalogue-desktop.png", fullPage: true });
  await page.getByRole("button", { name: "Drinks", exact: true }).click();
  await expect(page.locator(".product-card")).toHaveCount(1);
  await page.getByRole("button", { name: "All", exact: true }).click();
  const milk = page.locator(".product-card").filter({ has: page.getByRole("heading", { name: "Fresh full-cream milk" }) });
  await milk.getByRole("button", { name: "Add to basket" }).click();
  await page.getByRole("button", { name: "Sign in to place order" }).click();
  await page.getByRole("button", { name: "Fill demo details" }).click();
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await expect(page.locator(".verified-account")).toContainText("Ava Thompson");
  await page.getByRole("button", { name: "Place my order", exact: true }).click();
  await expect(page.getByRole("heading", { name: "A little goodness, reserved." })).toBeVisible();
  await expect(page.locator(".confirmation-details")).toContainText("$3.20");
  await page.getByRole("link", { name: "View my order" }).click();
  await expect(page.getByRole("heading", { name: "Edit your favourites." })).toBeVisible();
  await page.getByRole("button", { name: "Increase Fresh full-cream milk" }).click();
  await page.getByRole("button", { name: "Save my changes" }).click();
  await expect(page.locator(".confirmation-details")).toContainText("$6.40");
  expect(errors).toEqual([]);
});
test("mobile catalogue and sign-in have no horizontal overflow", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/");
  await expect(page.getByRole("heading", { name: "This cycle’s good things." })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: "docs/screenshots/catalogue-mobile.png", fullPage: true });
  await page.getByRole("link", { name: "Sign in", exact: true }).click();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await expect(page.getByLabel("Employee ID", { exact: true })).toBeVisible();
});
test("admin dashboard, product-photo editor, cycle control and PDF exports", async ({ page }) => {
  await page.goto("/admin");
  await expect(page.getByRole("heading", { name: "Welcome back." })).toBeVisible();
  await page.getByLabel("Username", { exact: true }).fill("demo-admin");
  await page.getByLabel("Password", { exact: true }).fill("AdminPantry2026!");
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Hello, Demo Administrator." })).toBeVisible();
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.screenshot({ path: "docs/screenshots/admin-desktop.png", fullPage: true });
  await page.getByRole("link", { name: "Catalogue", exact: true }).click();
  await page.getByRole("link", { name: "Add product" }).click();
  await expect(page.locator(".photo-option")).toHaveCount(6);
  await expect(page.locator('input[type="file"]')).toHaveCount(0);
  await page.getByRole("link", { name: "Orders & exports" }).click();
  const download = page.waitForEvent("download");
  await page.getByRole("button", { name: "Export Summary PDF" }).click();
  const file = await download;
  expect(file.suggestedFilename()).toMatch(/\.pdf$/);
  await file.saveAs(path.join("test-results", "summary.pdf"));
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: "docs/screenshots/admin-orders-mobile.png", fullPage: true });
  await page.getByRole("link", { name: "Sales cycles", exact: true }).click();
  await page.getByRole("link", { name: "Manage", exact: true }).first().click();
  page.once("dialog", dialog => dialog.accept());
  await page.getByRole("button", { name: "Close cycle" }).click();
  await expect(page.getByText("Status: closed", { exact: true })).toBeVisible();
  await page.goto("/");
  await expect(page.getByText("Orders are currently closed", { exact: true })).toBeVisible();
  await expect(page.locator(".product-card")).toHaveCount(0);
});
